# Default values for k8s-mediaserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

general: 
  ingress_host: k8s-test-loadbalancer.k8s.test
  plex_ingress_host: k8s-plex.k8s.test
  image_tag: latest
  #UID to run the process with
  puid: 1000
  #GID to run the process with
  pgid: 1000
  #Name, size and SC of needed PVC
  storage:
    pvcName: mediaserver-pvc
    size: 5Gi
    pvcStorageClass: []

sonarr:
  enabled: true
  container: 
    nodeSelector: {}
    port: 8989
  service:
    type: ClusterIP
    port: 8989
    nodePort: 
    extraLBService: false 
    # Defines an additional LB service, requires cloud provider service or MetalLB 

  ingress:
    enabled: true
    annotations: {}
    path: /sonarr
    tls:
      enabled: false
      secretName: ""

radarr:
  enabled: true
  container: 
    nodeSelector: {}
    port: 7878
  service:
    type: ClusterIP
    port: 7878
    nodePort: 
    extraLBService: false 
    # Defines an additional LB service, requires cloud provider service or MetalLB 

  ingress:
    enabled: true
    annotations: {}
    path: /radarr
    tls:
      enabled: false
      secretName: ""
  
jackett:
  enabled: true
  container: 
    nodeSelector: {}
    port: 9117
  service:
    type: ClusterIP
    port: 9117
    nodePort: 
    extraLBService: false 
    # Defines an additional LB service, requires cloud provider service or MetalLB 
  ingress:
    enabled: true
    annotations: {}
    path: /jackett
    tls:
      enabled: false
      secretName: ""
  
transmission:
  enabled: true
  container: 
    nodeSelector: {}
    port: 
      utp: 9091
      peer: 51413
  service:
    utp:
      type: ClusterIP
      port: 9091
      nodePort: 
      # Defines an additional LB service, requires cloud provider service or MetalLB 
      extraLBService: false
    peer:
      type: ClusterIP
      port: 51413
      nodePort:
      nodePortUDP: 
      # Defines an additional LB service, requires cloud provider service or MetalLB 
      extraLBService: false
  ingress:
    enabled: true
    annotations: {}
    path: /transmission
    tls:
      enabled: false
      secretName: ""
  config:
    auth: 
      enabled: false
      username: ""
      password: ""

sabnzbd:
  enabled: true
  container: 
    nodeSelector: {}
    port: 
      http: 8080
      https: 9090
  service:
    http:
      type: ClusterIP
      port: 8080
      nodePort: 
      # Defines an additional LB service, requires cloud provider service or MetalLB 
      extraLBService: false
    https:
      type: ClusterIP
      port: 9090
      nodePort:
      # Defines an additional LB service, requires cloud provider service or MetalLB 
      extraLBService: false
  ingress:
    enabled: true
    annotations: {}
    path: /sabnzbd
    tls:
      enabled: false
      secretName: ""

plex:
  enabled: true
  claim: "CHANGEME"
  replicaCount: 1
  container: 
    nodeSelector: {}
    port: 32400
  service:
    type: ClusterIP
    port: 32400
    nodePort: 
    # Defines an additional LB service, requires cloud provider service or MetalLB 
    extraLBService: false 
  ingress:
    enabled: true
    annotations: {}
    tls:
      enabled: false
      secretName: ""


