name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Renovate
        uses: renovatebot/github-action@v41.0.18
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate-app.json
        env:
          LOG_LEVEL: debug
